# Generated by Django 5.0.6 on 2024-05-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Загрузите изображение товара',
                null=True,
                upload_to='catalog/products',
                verbose_name='Изображение товара',
            ),
        ),
    ]
