# Generated by Django 4.2.13 on 2024-06-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={
                'ordering': ['category', 'price'],
                'permissions': [
                    ('can_change_publication_product', 'Может отменять публикацию товара'),
                    ('can_change_description_product', 'Может менять описание товара'),
                    ('can_change_category_product', 'Может менять категорию товара'),
                ],
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='publication',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
